# Generated by Django 3.1.7 on 2021-03-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
